name: Bump cert-manager helm chart version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://charts.jetstack.io
      name: cert-manager

targets:
  updateChartVersion:
    name: "jetstack/cert-manager Helm Chart"
    kind: yaml
    spec:
      files:
        - clusters/privatek8s.yaml
        - clusters/publick8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'cert-manager')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `cert-manager` helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - cert-manager
