name: Bump falco helm chart version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://falcosecurity.github.io/charts
      name: falco

targets:
  updateChartVersion:
    name: "falco/falco Helm Chart"
    kind: yaml
    scmid: default
    spec:
      files:
       - clusters/publick8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'falco')].version

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `falco` helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - falco
