name: "Bump incrementals-publisher Helm Chart Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: incrementals-publisher

targets:
  updateChartVersion:
    name: "Update the chart version for incrementals-publisher"
    kind: yaml
    spec:
      file: clusters/publick8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'incrementals-publisher')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `incremental-publisher` helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - incrementals-publisher
