name: "Bump jenkinsistheway.io redirection Helm Chart Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: httpredirector

targets:
  updateChartVersion:
    name: "Update the chart version for jenkinsistheway.io redirection"
    kind: yaml
    spec:
      file: clusters/publick8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'jenkinsisthewayio-redirect')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump jenkinsistheway.io redirection helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - jenkinsisthewayio-redirection
        - httpredirector
