name: "Bump jenkins-infra/jenkins-jobs Helm Chart Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: jenkins-jobs

targets:
  updateChartVersionPrivate:
    name: "Update the chart version for jenkins-jobs"
    kind: yaml
    spec:
      files:
        - clusters/privatek8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'jenkins-infra-jobs')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `jenkins-jobs` helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - jenkins-jobs
