name: "Bump rss2twitter Helm Chart Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    name: get last chart version
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: rss2twitter

targets:
  updateChartVersion:
    name: "Update the chart version for rss2twitter"
    kind: yaml
    spec:
      file: clusters/privatek8s.yaml
      engine: yamlpath
      key: $.releases[?(@.name == 'rss2twitter')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `rss2twitter` helm chart version to {{ source `lastChartVersion` }}
    spec:
      labels:
        - dependencies
        - rss2twitter
