# TODO: track with updatecli (from https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json)
nodeSelector:
  kubernetes.io/arch: arm64
  jenkins: ci.jenkins.io
  role: applications

# TODO: track with updatecli (from https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json)
tolerations:
  - key: "ci.jenkins.io/applications"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

resources:
  limits:
    # No CPU limit to avoid throttling
    memory: 4096Mi
  requests:
    cpu: 1.5
    memory: 4096Mi

service:
  type: LoadBalancer
  annotations:
    # Internal LB, with fixed IP in private subnet where EC2 VM agents are running
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    # We want the LB to directly send requests to the Pod IPs (requires VPC-CNI)
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-031fd3566ba47fd32,subnet-0138ee90cd53d58f7,subnet-012e4bea8ebb3a5fb"
    # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "10.0.131.247,10.0.129.247,10.0.151.247"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
    # Misc.
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: "HTTP2Preferred"

proxy:
  enabled: true
  remoteurl: "https://registry-1.docker.io"

persistence:
  enabled: true
  deleteEnabled: true
  size: "250Gi"
  # TODO: track with updatecli (from https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/47a0758f6f414fa12a2e8be54bd66e921f8a942a/eks-cijenkinsio-agents-2.tf#L217)
  # Same as ACP
  storageClass: ebs-csi-premium-retain-us-east-2a

## Init containers to add to the Deployment
# - name: init
#   image: busybox
#   command: []
initContainers:
  - name: permission-fix
    image: "busybox"
    command: ['chown', '-R', '1000:1000', '/var/lib/registry']
    volumeMounts:
      - mountPath: /var/lib/registry
        name: data
